#!/usr/bin/env python
from __future__ import print_function
import argparse
import pickle


def main(param_file, k_poins_file, show, save):

    import matplotlib.pyplot as plt
    import numpy as np
    import hamiltonian as hm
    from aux_functions import dict2xyz, yaml_parser, get_k_coords

    params = yaml_parser(param_file)

    if k_poins_file is None:
        if len(params['primitive_cell']) == 3:
            sym_points = ['L', 'GAMMA', 'X', 'W', 'K', 'L', 'W', 'X', 'K', 'GAMMA']
            num_points = [15, 20, 15, 10, 15, 15, 15, 15, 20]
            kk = get_k_coords(sym_points, num_points)
        else:
            kk = [[0.0, 0.0, 0.0]]
    else:
        kk = np.loadtxt(k_poins_file)

    h = hm.initializer(**params)
    h.set_periodic_bc(primitive_cell=params['primitive_cell'])

    band_structure = {}

    for j, jj in enumerate(kk):
        vals, vects = h.diagonalize_periodic_bc(jj)
        band_structure[j] = {'wave_vector': jj, 'eigenvalues': vals, 'eigenvectors': vects}
        print('#{} '.format(j), len(vals) * '{:2f} '.format(*np.real(vals)))

    band_structure = np.array([band_structure[item]['eigenvalues'] for item in xrange(len(band_structure))])

    if show:
        ax = plt.axes()
        ax.plot(np.sort(np.real(band_structure)))
        plt.show()

    if save:
        with open('./band_structure.pkl', 'wb') as f:
            pickle.dump(band_structure, f, pickle.HIGHEST_PROTOCOL)



parser = argparse.ArgumentParser()

parser.add_argument('param_file', type=str,
                    help='path to the yaml file containing parameters')

parser.add_argument('--k_points_file', type=str, default=None,
                    help='path to the file containing k points coordinates')

parser.add_argument('--show', '-S', type=bool, default=True,
                    help='show figures')

parser.add_argument('--save', '-s', type=bool, default=True,
                    help='save results of computations on disk')

args = parser.parse_args()
main(args.param_file, args.k_points_file, args.show, args.save)
